### ISSUE TITLE
Add random stats to waifus

### ISSUE THREAD

**Issue by Karitham** [Karitham/WaifuBot#20]
# What 

Have waifus have stats that represent rarity and some sort of strengh, useful for some planned features

# Why

More diversity in rolled waifus, also allow users to interact in the future with their waifus, maybe with items etc

# Progress

- [ ] Discuss what stats to be add
- [ ] Add those to the database
- [ ] Review existing's waifus case

**Comment by LaneSh4d0w** [comment]
Here's my vision of things : 

- Basic data : Strength, Agility, Magic, Charm, Precision.

- Based on the serie's genre, stats will be randomly (but finely linked) given to waifus. For example : Livaï Ackerman. The anime that matches this character is Attack on Titan. Strength and Precision will be better or more taken into consideration than other stats mentioned.

**Comment by LaneSh4d0w** [comment]
Genres can be asked using AniList's GraphQL, when the corresponding Anime is told, the bot can go search the Anime at the same instance, by adding the anime ID to the GraphQL request. This will permit to get the genre.

Best way to go is to analyze each genre that exists (or the most common) and make a base STAT form.

Example : 

BASE STATS : STR 20, AGI 20, MAG 20, CHM 20, PRE 20.

Character 125 comes from an Action -> Yandere anime.

Yandere tag : +5 STR, +2 AGI, -5 MAG, +1 or +2 CHM, +7 PRE.

**Comment by Karitham** [comment]
Would having 2 Megumin with different stats be innacurate for you ?

Maybe we could use your first suggestion but have a random rarity stat or something.

I kind of like this way of doing with the tags, should we consider all tags or only one ?

I don't think having another database for each character would be beneficial, as I'm trying to make this as lightweight as possible.

**Comment by LaneSh4d0w** [comment]
This would create inequalities between waifus, as one would be for example slightly better than another one.

Sounds about right about the rarity.

The first 3 should represent at least the majority of the anime, as it is related to user-voting or some sort of algorithm analysis.

It would be another entry in the database, nothing much. No need to do a separate database for that.

**Comment by LaneSh4d0w** [comment]
Here's how code vision could be:

- + Struct Stats containing

`int STR ""
int MAG ""
int CHR ""
int AGI ""
int PRC ""
bool isRare "false" // will need to be fixed to be random. (not like one each 200 or 300 rolls or hints.)`

- Initializing all stats with a certain number, to begin with.

- Waifus, when being rolled and / or claimed will get randomized stats, including a rarity state, adding +5 or +10 to specific stats.

- The way stats will be calculated depends on our method.
