### ISSUE TITLE
[Feature Request] - Lost characters

### ISSUE THREAD

**Issue by Ziloxeur** [Karitham/WaifuBot#50]
**Is your feature request related to a problem? Please describe.**
Someone gaves me a character already in my list and when I checked it, he was neither in mine and his. 

**Describe the solution you'd like**
I would like to be able to stack duplicate character gained in trade. 

**Describe alternatives you've considered - optional**
Gimme back my lost character :'(

**Comment by LaneSh4d0w** [comment]
It would mean verifying if the user has already got it, if the user has got it then the give is blocked. If it's not, then it's good to go. 

Just reuse the "verify" function you implemented and place it before the DB rewrite.

**Comment by Karitham** [comment]
There is no issue to having multiple time the same character as it is just stored as a mongo array,

I'll look deeper into the code, but as I see it there shouldn't be an issue like this with the current code, I may work more on this if it reiterates
