### ISSUE TITLE
[Feature Request] - add : sorting list by anime name of the characters

### ISSUE THREAD

**Issue by JackyOfSpades** [Karitham/WaifuBot#71]
_My feature request :_ 
It could be great to have all the characters of a certain anime (all seasons included) displayed together.
Plus you can add the feature of sorting on your own waifugui.kar with a better integration.  

_The solution i propose :_
It can be done by collecting the anime name and just sorting by alphabet order, you can just add it with the sorting on legonauzor gui (or your own gui)

_An alternative :_ 
Just adding a sorting feature on your own gui.

**Comment by JackyOfSpades** [comment]
i thinked you could just sort by alphabet letters like for characters but with the first anime/manga name to show that the character appears in. (by just sorting like this it should just appears in the right order)

**Comment by Karitham** [comment]
Currently, lists are sorted by date. Using the external API allows us to sort any-way we want, (using the website too).

Closing since this is now kind of irrelevant
