### ISSUE TITLE
[Feature Request] - Profile customization

### ISSUE THREAD

**Issue by Asarck** [Karitham/WaifuBot#74]
**Profile customization**
It should be a good idea to add the link of your Anilist.co profile, in order to see additional information about someone, as their favorite waifus, which can be something useful for trading with others, and maybe a future feature for the waifugui.

**Comment by Karitham** [comment]
Right, this is mostly why I added the quote feature at the start, to be able to link anything you want to.

However, this feels like a really good idea for a seperate field; what do you have in mind for the command?

We could go with a `profile edit` and migrate `quote` and `favorite` there, to be able to add more fields later on.

Would restriciting this to anilist be the right choice?

It would enable us to do easy linking and simpler comparison in WGUI, but some people also use MAL or other websites?

Thanks for the idea

**Comment by Asarck** [comment]
> **We could go with a `profile edit` and migrate `quote` and `favorite` there, to be able to add more fields later on.**

For this, i don't really know, i don't think there's that much data to add concerning the profile of someone.
And for the `Profile Edit`, i don't really understand what you mean by that, is it like the `search` function where you choose what thing you are looking for as `Character`/`Manga`/`Anime`. If it's this, then why not.

> **Would restriciting this to anilist be the right choice?

It would enable us to do easy linking and simpler comparison in WGUI, but some people also use MAL or other websites?**
I don't really know if MAL have the same feature about the "Favorite characters"/"Favorite waifus".
I though about using Anilist only because it's where you retrieve data since the beginning, so maybe try it with anilist atm, and maybe add more account links later.

**Comment by Karitham** [comment]
> For this, i don't really know, i don't think there's that much data to add concerning the profile of someone.
And for the Profile Edit, i don't really understand what you mean by that, is it like the search function where you choose what thing you are looking for as Character/Manga/Anime. If it's this, then why not.

Yes I was speaking about subcommands, just like how `search` and `trending` are implemented currently, which enables us to save shorter names for other stuff. 

> I don't really know if MAL have the same feature about the "Favorite characters"/"Favorite waifus".

No idea about that, was wondering if even allowing MAL links would be a good idea, we can enforce only anilist links if we want, but not sure that's beneficial. A general "profile url" would probably make more sense.

**Comment by Karitham** [comment]
Implemented anilist, I don't want to also implement MAL but can be done as a PR if anyone wants it.
