### ISSUE TITLE
Events Order for claims

### ISSUE THREAD

**Issue by Asarck** [Karitham/WaifuBot#81]
# Pull Request 12 December 2021 : Events Order for claims
>As-is

New Claim
Someone Guess the Name
Bot roll for a new claim
Bot check the Message of the User
Bot validate or not the claim
>To-be

New Claim
Someone guess the name
Bot check the Message of the User
Bot validate or not the claim
Bot roll for a new claim

**Comment by Karitham** [comment]
Should be fixed with b570e974c499be5e7dbe17ffefd225bd1ded5523, closing
