### ISSUE TITLE
[Feature Request] - add : token system

### ISSUE THREAD

**Issue by Netherchaotic** [Karitham/WaifuBot#82]
My feature request : 
I would like to be able to exchange my characters that I am not interested in in my list against the possibility of making a free roll. This could be a useful feature to recycle our characters and reduce the size of our list.

The solution I propose :
It can be something like you get tokens when you /discard a character, and each 3, 4 or 5 tokens gives you the possibility to make a free bonus roll.

**Comment by LaneSh4d0w** [comment]
@Karitham will correct me if he finds something better but the idea could be : 

- Add a "token" row inside each person
- Implement a "exchange" function in which : 
  - Contacts the bot for a potential exchange (the bot's list won't count)
  - Verifies the user ID, checks DB for potential tokens, and if the number of tokens is equivalent to a free roll, asks user if he wants to roll a new character.
  - If answer is yes, remove the equivalent number of tokens off the user's data, and roll a waifu.
  - If answer is no, simply add a token upon character confirmation in the user's data.

**Comment by Karitham** [comment]
Currently, a the roll function with a similar idea is implemented on branch #corde, but I haven't implemented anything for exchanging against tokens. The `exchange` name is great, though

**Comment by Karitham** [comment]
Implemented in corde
