### ISSUE TITLE
Interaction fails with new Users

### ISSUE THREAD

**Issue by cloudofdarkhole6** [Karitham/WaifuBot#89]
When a User that isnt registered yet in the database tries to use /roll or other features, it fails with the message "this interaction failed".
![unknown](https://user-images.githubusercontent.com/28675683/194769199-fccf7b36-ae2c-4c02-9881-f8daaf225eac.png)

Trying to give these users a character via /give also fails, so they are effectivly locked out of using the bot.
Other users in my server that have been using the bot for a long time already can use it without troubles.

**Comment by Le-Roux-nard** [comment]
It happened to me with both of my accounts on a server where they are owner/administrator.
I don't know if there is something that can be done to be able to use every commands

**Comment by Karitham** [comment]
sorry for taking so long, fixed with 2e05527a21a6997ef260c7bf41d81ae5ee6f403c

**Comment by Karitham** [comment]
If you have any more issues, feel free to add more detail and I can directly fix issues that are not so generic.
